exported label and helperText components
MeasureAuthoringTool/madie-components pull request #13
Opened 2021-11-05 17:08 UTC by RohitKandimalla

2021-11-05 17:37 UTC, jkotanchik-SB submitted a review, later dismissed

2021-11-05 22:21 UTC, AndrewBird81 requested changes

2021-11-05 22:21 UTC, AndrewBird81 commented on src/madie-madie-components.tsx
> +export { default as LabelComponent } from "./components/labels/Label";
Can we just call it "Label"?

2021-11-07 20:04 UTC, RohitKandimalla commented on src/madie-madie-components.tsx
> +export { default as LabelComponent } from "./components/labels/Label";
Done

2021-11-08 14:42 UTC, jkotanchik-SB approved these changes

2021-11-08 14:45 UTC, AndrewBird81 approved these changes

2021-11-08 14:45 UTC, merged